services:
  db:
    image: postgres:12.19
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=MinhaLanchonete
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

