name: CI

on: [ push ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: yezz123/setup-uv@v4
        with:
          uv-venv: "venv"
      - name: Test with pytest
        run: |
          uv run pytest
