name: Deploy

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Clonar o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Fazer login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extrair metadados para a imagem
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.IMAGE_NAME }}

      # Construir e publicar a imagem no Docker Hub
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
