name: Deploy

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      PRODUCTION:
        required: true
        type: boolean

    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

  deploy-homolog:
    if: ${{inputs.PRODUCTION!=true}}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Homolog
        run: echo "Deploying to Homolog"

  deploy-prod:
    if: ${{inputs.PRODUCTION==true}}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Homolog
        run: echo "Deploying to Homolog"
