name: Pipeline CI/CD

on:
  push:

jobs:
  CI:
    uses: ./.github/workflows/ci.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  CD:
    needs: CI
    uses: ./.github/workflows/deploy.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    with:
      IMAGE_NAME: ambrosia-serve
